export const dummyData = [
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 July, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
  {
    companyName: "Axie Infinity",
    auditDate: "12 Aug, 2024",
    auditId: "118",
    image: "/assets/images/audits-page-logo.svg",
  },
];
export const auditsCard2 = [
  {
    topic: "CRITICAL",
    value: 1,
  },
  {
    topic: "Medium",
    value: 8,
  },
  {
    topic: "LOW",
    value: 2,
  },
  {
    topic: "INFORMATIONA",
    value: 26,
  },
  {
    topic: "OPTIMIZATIONS",
    value: 0,
  },
];
