export const authorsData = [
  {
    image: "/assets/images/authors/ram-kumar.svg",
    name: "Mr. Ram Kumar",
    designation: "Blockchain Security Expert",
    education: "B. Tech (IIT Kanpur)",
    twitter: "x.com",
    linkedin: "linkedin.com",
  },
  {
    image: "/assets/images/authors/shyam-patel.svg",
    name: "Dr. Shyam Patel",
    designation: "Web3 Security Specialist",
    education: "B.Tech, M. Tech (VTU)",
    twitter: "x.com",
    linkedin: "linkedin.com",
  },
  {
    image: "/assets/images/authors/kartikeya-k.svg",
    name: "Mr. Kartikeya K",
    designation: "Blockchain Security Architect",
    education: "(Amity University, B Tech)",
    twitter: "x.com",
    linkedin: "linkedin.com",
  },
  {
    image: "/assets/images/authors/irfan-ansari.svg",
    name: "Dr. Irfan Ansari",
    designation: "Web3 Security Analyst",
    education: "",
    twitter: "x.com",
    linkedin: "linkedin.com",
  },
  {
    image: "/assets/images/authors/hemlatha-s.svg",
    name: "Ms. Hemlatha S",
    designation: "Blockchain Security Consultant",
    education: "(B.E, Delhi College of Engineering)",
    twitter: "x.com",
    linkedin: "linkedin.com",
  },
  {
    image: "/assets/images/authors/rashmi-bansal.svg",
    name: "Mrs. Rashmi Bansal",
    designation: "Blockchain Architecture &",
    education: "Consultant Cyber Security (MCA)",
    twitter: "x.com",
    linkedin: "linkedin.com",
  },
];
