export const authorsData = [
  {
    to: "ram-kumar",
    image: "/assets/images/authors/ram-kumar.svg",
    name: "Mr. Ram Kumar",
    designation: "Blockchain Security Expert",
    education: "B. Tech (IIT Kanpur)",
    twitter: "x.com",
    linkedin: "linkedin.com",
    details: [
      {
        title: "Experience",
        info: "Ram Kumar has a proven track record in safeguarding blockchain projects, with a focus on smart contract security and vulnerability assessment. His experience spans a wide range of blockchain platforms and technologies.",
      },
      {
        title: "Expertise",
        info: "Ram possesses deep expertise in cryptographic algorithms, security protocols, and blockchain governance. He is skilled in identifying and mitigating various security threats, including exploits, denial-of-service attacks, and privacy breaches.",
      },
      {
        title: "Authoritativeness",
        info: "Ram is widely recognized as a leading authority in the field of blockchain security. His contributions to the community and publications have solidified his reputation as a trusted expert.",
      },
      {
        title: "Trustworthiness",
        info: "Ram is known for his integrity and commitment to providing the highest level of security services. His clients trust him to protect their digital assets and maintain the confidentiality of their sensitive information.",
      },
    ],
  },
  {
    to: "shyam-patel",
    image: "/assets/images/authors/shyam-patel.svg",
    name: "Dr. Shyam Patel",
    designation: "Web3 Security Specialist",
    education: "B.Tech, M. Tech (VTU)",
    twitter: "x.com",
    linkedin: "linkedin.com",
  },
  {
    to: "kartikeya-k",
    image: "/assets/images/authors/kartikeya-k.svg",
    name: "Mr. Kartikeya K",
    designation: "Blockchain Security Architect",
    education: "(Amity University, B Tech)",
    twitter: "x.com",
    linkedin: "linkedin.com",
  },
  {
    to: "irfan-ansari",
    image: "/assets/images/authors/irfan-ansari.svg",
    name: "Dr. Irfan Ansari",
    designation: "Web3 Security Analyst",
    education: "",
    twitter: "x.com",
    linkedin: "linkedin.com",
  },
  {
    to: "hemlatha-s",
    image: "/assets/images/authors/hemlatha-s.svg",
    name: "Ms. Hemlatha S",
    designation: "Blockchain Security Consultant",
    education: "(B.E, Delhi College of Engineering)",
    twitter: "x.com",
    linkedin: "linkedin.com",
  },
  {
    to: "rashmi-bansal",
    image: "/assets/images/authors/rashmi-bansal.svg",
    name: "Mrs. Rashmi Bansal",
    designation: "Blockchain Architecture &",
    education: "Consultant Cyber Security (MCA)",
    twitter: "x.com",
    linkedin: "linkedin.com",
  },
];
